test: paragraph_with_url, header_with_url
izyuumi/html2md-rs pull request #7
Opened 2024-03-02 07:36 UTC by yutatokoi

2024-03-02 21:58 UTC, izyumidev commented
Please resolve conflicts first.

2024-03-08 17:26 UTC, izyuumi requested changes

2024-03-08 17:26 UTC, izyuumi commented on tests/to_md_tests.rs
> +        let expected "# ## hello\n".to_string();
No `=`

2024-03-08 17:26 UTC, izyuumi commented on tests/to_md_tests.rs
> +        let expected "## # hello\n".to_string();
same as above

2024-04-01 12:09 UTC, closed without merging